# Use an official Python runtime as a base image
FROM python:3.12.6

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the container
COPY requirements.txt .

# Install any dependencies
RUN pip install --upgrade pip

# Install the dependencies
RUN pip install -r requirements.txt


# Copy the application files to the container
COPY . .

# Specify the command to run your application
CMD ["python", "new_main.py"]
