# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: machinelearning.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'machinelearning.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15machinelearning.proto\x12\x0fmachinelearning\"/\n\x0ePredictRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06userID\x18\x02 \x01(\x03\"9\n\x0fPredictResponse\x12\x15\n\rserviceStatus\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2f\n\x16MachineLearningService\x12L\n\x07Predict\x12\x1f.machinelearning.PredictRequest\x1a .machinelearning.PredictResponseB7Z5Public-automated-check-in/machinelearning/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'machinelearning_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5Public-automated-check-in/machinelearning/proto;proto'
  _globals['_PREDICTREQUEST']._serialized_start=42
  _globals['_PREDICTREQUEST']._serialized_end=89
  _globals['_PREDICTRESPONSE']._serialized_start=91
  _globals['_PREDICTRESPONSE']._serialized_end=148
  _globals['_MACHINELEARNINGSERVICE']._serialized_start=150
  _globals['_MACHINELEARNINGSERVICE']._serialized_end=252
# @@protoc_insertion_point(module_scope)
