# Stage 1: Build the Go binary
FROM golang:1.23 AS builder

WORKDIR /workspace

# Copy the Go module files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the entire project source code
COPY . .

#"   C:\Users\alexa\SanderStuff\p5\Public-automated-check-in\\cmd\checkinserver
# Build the binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o updatestatus ./cmd/checkinserver/main.go

# Stage 2: Create a minimal image for running the app
FROM alpine:latest

WORKDIR /workspace

# Copy the binary from the builder stage
COPY --from=builder /workspace/updatestatus .

# Command to run the application
CMD ["/workspace/updatestatus"]


