/**
 * @fileoverview gRPC-Web generated client stub for mystirng
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: mystirng.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as mystirng_pb from './mystirng_pb'; // proto import: "mystirng.proto"


export class SplitterClient {
	client_: grpcWeb.AbstractClientBase;
	hostname_: string;
	credentials_: null | { [index: string]: string; };
	options_: null | { [index: string]: any; };

	constructor(hostname: string,
		credentials?: null | { [index: string]: string; },
		options?: null | { [index: string]: any; }) {
		if (!options) options = {};
		if (!credentials) credentials = {};
		options['format'] = 'text';

		this.client_ = new grpcWeb.GrpcWebClientBase(options);
		this.hostname_ = hostname.replace(/\/+$/, '');
		this.credentials_ = credentials;
		this.options_ = options;
	}

	methodDescriptorSplitString = new grpcWeb.MethodDescriptor(
		'/mystirng.Splitter/SplitString',
		grpcWeb.MethodType.UNARY,
		mystirng_pb.StringRequest,
		mystirng_pb.StringResponse,
		(request: mystirng_pb.StringRequest) => {
			return request.serializeBinary();
		},
		mystirng_pb.StringResponse.deserializeBinary
	);

	splitString(
		request: mystirng_pb.StringRequest,
		metadata?: grpcWeb.Metadata | null): Promise<mystirng_pb.StringResponse>;

	splitString(
		request: mystirng_pb.StringRequest,
		metadata: grpcWeb.Metadata | null,
		callback: (err: grpcWeb.RpcError,
			response: mystirng_pb.StringResponse) => void): grpcWeb.ClientReadableStream<mystirng_pb.StringResponse>;

	splitString(
		request: mystirng_pb.StringRequest,
		metadata?: grpcWeb.Metadata | null,
		callback?: (err: grpcWeb.RpcError,
			response: mystirng_pb.StringResponse) => void) {
		if (callback !== undefined) {
			return this.client_.rpcCall(
				this.hostname_ +
				'/mystirng.Splitter/SplitString',
				request,
				metadata || {},
				this.methodDescriptorSplitString,
				callback);
		}
		return this.client_.unaryCall(
			this.hostname_ +
			'/mystirng.Splitter/SplitString',
			request,
			metadata || {},
			this.methodDescriptorSplitString);
	}

}

