FROM golang:1.23 AS builder

WORKDIR /workspace

COPY go.mod go.sum ./

RUN go mod download

COPY . .

# Build the binary for Linux
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server ./cmd/server/main.go

FROM alpine:latest

WORKDIR /workspace

COPY --from=builder /workspace/server .
COPY --from=builder /workspace/config/.env ./config/.env

EXPOSE 8080

CMD ["/workspace/server"]

