# Stage 1: Build the Go binary
FROM golang:1.23 AS builder

WORKDIR /workspace

# Copy the Go module files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the entire project source code
COPY . .

# Build the binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o authesp ./cmd/authEsp/main.go

# Stage 2: Create a minimal image for running the app
FROM alpine:latest

WORKDIR /workspace

# Copy the binary from the builder stage
COPY --from=builder /workspace/authesp .
COPY --from=builder /workspace/config/.env ./config/.env

# Expose the application port (adjust as needed)
EXPOSE 8050

# Command to run the application
CMD ["/workspace/authesp"]
